author= "Moataz Nagoudi, AbdelRahim Elmadany, and Muhammad Abdul-Mageed"
copyright= "Copyright 2022, University of British Columbia (UBC), Deep learning and Natural Langauge Processing Lab"
license= "GPL"
version= "1.0.2"
email= "a.elmadany@ubc.ca"
status= "Production"
description="TURJUMAN, a neural toolkit for translating from 20 languages into Modern Standard Arabic (MSA)."